### ISSUE TITLE
[LEGACY] [0000] Overall tracker distance to server deployment

### ISSUE THREAD

**Issue by mwpowellhtx** [mwpowellhtx/KP-Liberation#116]
### Basic Information
**Mission version:** `v0.97.0a`
**Map used:** `Altis`
**Mods used:** _Base set_, including `ACE`, `RHS`
**Dedicated or local game:** `Local` (for now)

### Short Issue Description
Logging this issue to track overall progress, and to monitor scope, keeping that contained as possible, while still achieving couple of bare minimum goals we want to do in the legacy framework.
- [x] [Rebase master](113) from source origin; may establish a brand new `legacy` branch if at all possible
- [x] Improve robustness of [managed assets](115) i.e. _huron_, i.e. when _placeholders_ are not present
- [x] Improve robustness of [start vehicle spawn](112), allowing for more scenarios, and possibilities for gaps, etc
- [x] Review deeply [preset sides](114), factions, establish good baselines, then perhaps get more unit specific
- [ ] Add unit specific images, artwork, splash, join, tutorial, flags, etc; also pull some in game billboard images, ROE and generally server rules, as well as recruitment notes.
- [ ] Review framework configuration, establish sensible defaults
- [x] Review CBA server side settings, which ones are allowable client side, etc
- [x] Wrap up the _Altis_ map vis-a-vis the slot and framework bits; [rinse and repeat in the other maps](133)
- [x] Consider 1-3 other maps to introduce keeping the rotation fresh, drawing visitors, etc

### Expected Behaviour
Work in progress.

**Comment by mwpowellhtx** [comment]
Will append as we have things to consider:
- [x] Look into the conditions for the [_mobile respawn_](119); when marker created, update, deleted, and why the cycle never seems to settle. Perhaps some conditions need to be resolved in that area. Also address obvious issues, such as the _momentum_ condition, which last time we checked, was considering only _positive_ i.e. _forward momentum_, _negative_ i.e. _backward_, resulting in _markers shown_.

**Comment by mwpowellhtx** [comment]
- [x] Enhance the [_ROE accountability_](120). In the case of [_buildings_](120), considering that one either _laziness_, or just an _inappropriate accounting_ of buildings, i.e. regardless of _spawn points_, and perhaps also _exits_ in some cases.

**Comment by mwpowellhtx** [comment]
- [x] Incorporate [ACRE](124) radio channel plan

**Comment by mwpowellhtx** [comment]
- [x] Address odd _ACE loadout corruption_ issues. There is some dynamic between _ACE virtual arsenal_, and perhaps also _check gear_, _custom allowed classes_ going on.
- [x] Add ACE vehicle lock keys, add parameter

We decided to forego _checking gear_, at least for _legacy_ purposes. Whatever was going on baseline code, not worth redressing that in this version of our career. Instead, configuring parameters **_directly_** to _ACE virtual arsenal_. This seems to work just fine for the time being.

**Comment by mwpowellhtx** [comment]
- [ ] Esbablish and tweak _server side configuration_; we also want to decide on where we should be configuring appropriate difficulty levels, including the blessed _custom_ level. Done the first part, but need to pull together, probably, a [_FASTER_](https://github.com/Foxlider/FASTER) configuration, including the server side configuration aspects. Probably.

To clarify, not in game CBA settings, but rather _the actual server executable_, and its `.cfg` properties.

**Comment by mwpowellhtx** [comment]
Did review _CBA settings_ top to bottom, much of which for ACE and so forth. For the most part, done, may need to tweak a few. Saved them out to profile, if possible, may want to obtain a clipboard copy and back them up that way. Decided which are _server side_, overriding even the mission, as well as leaving a handful open for both _mission_, as well as _player_, discretion.

**Comment by mwpowellhtx** [comment]
- [x] Put in [corrective measures](125) accounting for _buildings damaged_ or _destroyed_, to include whether those have _positions_ and/or _paths_ or _exits_.

**Comment by mwpowellhtx** [comment]
- [x] Redressed _TeamSpeak_ rank icons channel group assignments; except for a handful upper echelon or specialized ranks, should be good to go for most member requirements. Shall be done at the _channel group_ level, not server, since the server supports several different sorts of applications, one of them being _ArmA III_. Bit different, perhaps, than some units run theirs.
- [x] Pulled down the WO rank insignia as well. Will upload those when we get around to it.

**Comment by mwpowellhtx** [comment]
- [ ] Worked on a bit of [_discord channeling_](126) and other socials elements.

**Comment by mwpowellhtx** [comment]
- [x] Remediate build menu re: [disable infantry build](127) capability in all its forms.
- [x] Also addressed [squad size contraints](128) at the same time

**Comment by mwpowellhtx** [comment]
Introduced _NATO USMC_ _woodland_ and _desert_ variants. Verified models are all as closely _USMC_ as possible. One of three _army_ stragglers may still be there. The brush strokes are somewhat broad in terms of _enumerated models_, _costs_, etc. So, will distill this into a more official unit faction, both _woodland_ and _desert_ variants.

- [x] Still pending is to review appropriate other side factions as well, usually map or _terrain specific_, i.e. for _Takisan_ versus an _Altis_ versus a _Chernarus_, along these lines, although we're thinking the defaults will be mostly fine. However, will aim for consistency as much as possible to mitigate the load.

**Comment by mwpowellhtx** [comment]
- [x] Settled on couple of flags, USMC variant, also unit flag, both working at start base.
- [x] Shifted from the KP flag in build menu to a unit flag in build menu.
- [x] Sorted out couple of billboard resources and got them connected to the appropriate objects.

**Comment by mwpowellhtx** [comment]
We think we have the core [_ROE accountability_](https://github.com/mwpowellhtx/KP-Liberation/issues/116#issuecomment-1724563376) properly declared for the most part. We'll see how that plays out in game and with some traffic, knock on wood.

**Comment by mwpowellhtx** [comment]
We may do some [_fine tuning_](https://github.com/mwpowellhtx/KP-Liberation/issues/116#issuecomment-1732194369) of various aspects, but we are pretty happy with how things are deploying at the moment.
