### ISSUE TITLE
[Triggers] [0001] Add the module

### ISSUE THREAD

**Issue by mwpowellhtx** [mwpowellhtx/KP-Liberation#88]
### Basic Information
**Mission version:** `v0.98.dev-s16`
**Map used:** _Altis_

### Short Issue Description
The [IED](87) effort also involved establishing a `TRIGGERS` module. Yes, we will most definitely use this for the [`IED` module](87), but will make an effort to extend support for this that is truly extensible.

This leans heavily on the [`CBA_fnc_createTrigger`](https://cbateam.github.io/CBA_A3/docs/files/common/fnc_createTrigger-sqf.html) function, but to be honest, [_Arma 3 Triggers_](https://community.bistudio.com/wiki/Category:Command_Group:_Triggers) fundamentals must be understood.

The core part of the module is the `KPLIB_fnc_triggers_create` function, most of which is pretty self-explanatory.

```sqf
_trigger = [
    _targetOrPos
    , _area
    , _activation
    , _statementCallbacks
] call KPLIB_fnc_triggers_create;
```

Most of the parameters may be better understood individually.

- [x] `_targetOrPos` may be a TARGET OBJECT (i.e. `objNull`) or a [_position_](https://community.bistudio.com/wiki/Position#Introduction).
- [x] [Area](https://community.bistudio.com/wiki/setTriggerArea), [_see comments_](https://github.com/mwpowellhtx/KP-Liberation/issues/88#issuecomment-835813716).
- [x] [Activation](https://community.bistudio.com/wiki/setTriggerActivation), [_see comments_](https://github.com/mwpowellhtx/KP-Liberation/issues/88#issuecomment-835813903).
- [x] [Statement callbacks](https://community.bistudio.com/wiki/setTriggerStatements), [_see comments_](https://github.com/mwpowellhtx/KP-Liberation/issues/88#issuecomment-835814311).

**Comment by mwpowellhtx** [comment]
_Triggers_ will pretty much run [_in perpetuity_](https://www.dictionary.com/browse/perpetuity) unless the caller or subscriber invokes the `KPLIB_fnc_triggers_onGC` function, which garbage collects them, removes them from the `KPLIB_triggers_registry`, and so forth.

**Comment by mwpowellhtx** [comment]
Review the [`setTriggerArea` _community docs_](https://community.bistudio.com/wiki/setTriggerArea) for a more in depth or connected material. The `_area` argument is pretty much _that_ self-contained.

The `C`, _Z divided by 2_, component, and is optional. When ommitted, the trigger extends to the heavenlies, but for most things you probably want to include it.

Default assumes _non-rectangular_, i.e. [_elliptic_](https://en.wikipedia.org/wiki/Ellipse). Also note, the `ANGLE` component informs the _direction_ affected by the `B`, _Y divided by 2_, component.

**Comment by mwpowellhtx** [comment]
Review the [`setTriggerActivation` _community docs_](https://community.bistudio.com/wiki/setTriggerActivation) for a bit more in depth background. The `_activation` argument is not exactly the same, and we allow for a bit more flexibility in the specification, especially that is type specific.

Overall, the argument is similar, `[_by, _type, _repeating]`, but we will elaborate on the allowed bits further.

- [x] `_by` (`SIDE`|`STRING`), see this comment below.
- [x] `_type` (`SIDE`|`BOOL`), see this comment below.
- [x] `_repeating` (`BOOL`), self-explanatory.

_Activation By_ may be either `SIDE` or `STRING`. We could not think of a better way to specify some aspects, but perhaps we will revise that assuming future discoveries, discussion, elaboration, etc. `SIDE` is typically aligned with `WEST` or `BLUFOR`, `EAST` or `OPFOR`, `RESISTANCE` (`GUER`), `CIVILIAN` (`CIV`), but may also be [`sideLogic`](https://community.bistudio.com/wiki/sideLogic). Any other argument returns for _any player_. A general use `STRING` may also be specified, but we have defined some preset values to help with that.

_Activation Type_ may be SIDE or BOOL, aligned with `KPLIB_preset_sideF`, `KPLIB_preset_sideE`, `KPLIB_preset_sideR`, or `KPLIB_preset_sideC`, respectively. Usually these are `WEST` or `BLUFOR`, `EAST` or `OPFOR`, `RESISTANCE` (`GUER`), `CIVILIAN` (`CIV`), respectively, but we allow for that flexibility, depending upon how subscribers have configured _friendly_, _enemy_, etc.

Some presets have been defined for use, for brevity, enumerating the choices in a sort of [_Domain Specific Language_](https://en.wikipedia.org/wiki/Domain-specific_language) (DSL), should be fairly self-explanatory, i.e. `KPLIB_preset_triggers_bySideEast`, `KPLIB_preset_triggers_typePresent`:

```
KPLIB_preset_triggers_bySide[East|West|Guer|Civ|Logic|Any|AnyPlayer]
KPLIB_preset_triggers_byRadio[Alpha|Bravo|Charlie|Delta|Echo|Foxtrot|Golf|Hotel|India|Juliet]
KPLIB_preset_triggers_byObject[Static|Vehicle|Group|Leader|Member]
KPLIB_preset_triggers_byStatus[East|West|Guer]
KPLIB_preset_triggers_type[Not]Present
KPLIB_preset_triggers_type[West|East|Guer|Civ]Detection
```

**Comment by mwpowellhtx** [comment]
Review the [`setTriggerStatements` _community docs_](https://community.bistudio.com/wiki/setTriggerStatements) for more in depth or connected material. The `_statementCallbacks` argument differs slightly from this in that we expect there to be actual `CODE`, either an _anonymous function_ given, or a _compiled_ of _configuration function_.

The module will relay the `STRING` _statements_, a it were, assuming the built-in magic `this` (`BOOL`), `thisTrigger` (`OBJECT`), `thisList` (`ARRAY`), variables, and will install _subscriber specified_ `CODE` or appropriate defaults.

```sqf
[
    _onCondition
    , _onActivation
    , _onDeactivation
]
```

Of note, we position arguments a bit differently than one might expect from the documentation. There is a method to the madness. We install the callbacks directly on the TRIGGER object itself and look it up via the module callback strings.

- [x] `_onCondition`, arguments are `[thisTrigger, thisList, this]`, in that order. Default `{_this#2}`, that is, simply returns the default condition. The _actual_ trigger condition, of course, may be anything, that is entirely up to the subscriber.
- [x] `_onActivation`, is the fundamental callback that occurs when the trigger _fires_, as it were. Arguments are `[thisTrigger, thisList]`, in that order. Default `{}`, i.e. _no-op_.
- [x] `_onDeactivation`, is the fundamental callback that occurs when the trigger is deactivated, as it were. Arguments are `[thisTrigger]`, in that order. Default `{}`, i.e. _no-op_.

For the curious, we reference things as such. Subscribers do not need to know about that, but maintainers might. Internally, we set and get the variables, and invoke the functions accordingly.

```sqf
_onCondition = _trigger getVariable ['KPLIB_fnc_triggers_onCondition', {_this#2}];
_onActivation = _trigger getVariable ['KPLIB_fnc_triggers_onActivation', {}];
_onDeactivation = _trigger getVariable ['KPLIB_fnc_triggers_onDeactivation', {}];
```

**Comment by mwpowellhtx** [comment]
Basically this one is _done_. If we need to follow up, open a new issue.

**Comment by mwpowellhtx** [comment]
When associated with a `TARGET` object, the `TARGET` object may be deleted from existence. When that occurs, the `TRIGGER` will detect that and also self-heal, i.e. be GC'ed.
